services:
  wordpress:
    build: .
    container_name: wordpress_app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      # O WordPress usa estas chaves para gerar o wp-config.php
      WORDPRESS_AUTH_KEY:         ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY:  ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY:    ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY:        ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT:        ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT:   ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT:       ${WORDPRESS_NONCE_SALT}
    volumes:
      # O volume para wp-content é essencial para persistir uploads, temas e plugins.
      - wp_content:/var/www/html/wp-content

volumes:
  wp_content: